apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - serviceaccount.yaml
  - deployment-web.yaml
  - service-web.yaml
  - hpa-web.yaml
  - pdb-web.yaml
  - networkpolicy-web.yaml
  - ingress.yaml