apiVersion: v1
kind: ServiceAccount
metadata:
  name: openlaunch
  namespace: openlaunch
  labels:
    app.kubernetes.io/name: openlaunch
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: openlaunch