{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openlaunch.fullname" . }}-secrets
  labels:
    {{- include "openlaunch.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}