apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openlaunch-dev
resources:
  - ../../overlays/dev
  - deployment-api.yaml
  - service-api.yaml
  - networkpolicy-api.yaml
images:
  - name: openlaunch-api:local
    newTag: dev
patches:
  - path: patch-ingress.yaml