apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: openlaunch-api
  namespace: openlaunch-dev
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: openlaunch
      app.kubernetes.io/component: api
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: openlaunch
              app.kubernetes.io/component: web
      ports:
        - protocol: TCP
          port: 4000
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53