# namespace/shared.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: openlaunch-local
  labels:
    app.kubernetes.io/part-of: openlaunch
    openlaunch.io/env: local
---
apiVersion: v1
kind: Namespace
metadata:
  name: openlaunch-dev
  labels:
    app.kubernetes.io/part-of: openlaunch
    openlaunch.io/env: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: openlaunch-prod
  labels:
    app.kubernetes.io/part-of: openlaunch
    openlaunch.io/env: prod
